name: ci
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          password: "${{ secrets.DOCKER_TOKEN }}"
          username: "${{ secrets.DOCKER_USERNAME }}"
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          cache-from: "type=registry,ref=${{ secrets.DOCKER_USERNAME }}/simplewhale:buildcache"
          cache-to: "type=registry,ref=${{ secrets.DOCKER_USERNAME }}/simplewhale:buildcache,mode=max"
          context: "."
          file: ./Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/opsworks:dev"
